services:
  - type: web
    name: vacation-agent
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: ANTHROPIC_API_KEY
        sync: false  # This will need to be set manually in Render dashboard
    healthCheckPath: /